version: '3.8'

services:
  app:
    build: .
    container_name: gesturno_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      CI_ENVIRONMENT: development
      APP_BASE_URL: http://localhost:8080
      DB_HOST: db
      DB_NAME: gesturno
      DB_USER: gesturno
      DB_PASS: gesturno123
    depends_on:
      - db
    networks:
      - gesturno_net

  db:
    image: mysql:8.0
    container_name: gesturno_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gesturno
      MYSQL_USER: gesturno
      MYSQL_PASSWORD: gesturno123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gesturno_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gesturno_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: gesturno
      PMA_PASSWORD: gesturno123
    depends_on:
      - db
    networks:
      - gesturno_net

volumes:
  db_data:

networks:
  gesturno_net:
